### ISSUE TITLE
Changes could not be commited.

### ISSUE THREAD

**Issue by vvadymv** [ChrisYounger/git_for_splunk#1]
I've installed and configured the app. Time to time I get notifications of error to email. The strange thing is that it mysteriously disappear and I see "GitForSplunk on splunk: [OK] Changes: 2, RepoSize:"  and appear again with no intervention from my side. 

GitForSplunk on splunk: [Error] Runtime: 0sec, 2019-08-30 15:53

Changes could not be commited.

GitForSplunk 1567169598
SPLUNK_HOME=/opt/splunk
GIT_WORK_TREE=/opt/splunk/etc/
GIT_DIR=/opt/splunk/etc/.git/
Running Btool for: inputs (rc=0)
Running Btool for: indexes (rc=0)
Running Btool for: fields (rc=0)
Running Btool for: props (rc=0)
Running Btool for: limits (rc=0)
Running Btool for: outputs (rc=0)
Running Btool for: props (rc=0)
Running Btool for: transforms (rc=0)
Running Btool for: savedsearches (rc=0)
Running Btool for: macros (rc=0)
COMMAND: git status
OUTPUT:On branch master
nothing to commit, working tree clean

EXITCODE: 0
COMMAND: git add --all
OUTPUT:

EXITCODE: 0
COMMAND: git commit -m auto
OUTPUT:On branch master
nothing to commit, working tree clean

EXITCODE: 1
An exception of type Exception occurred. Arguments:
('Error occured',)
runtime=0.297928
status=2

**Comment by vvadymv** [comment]
Is it possible that error rises in case of no changes to configs/repo ?

**Comment by ChrisYounger** [comment]
Yes that is correct. its because there were no changes. ill try get this handled better soon

**Comment by manderso7** [comment]
Can you think of a way to resolve this, or where I could start checking? We're seeing these a lot.

**Comment by ChrisYounger** [comment]
This error can be safely ignored. It just means that nothing has changed since the last time the app ran. 

I have been on long service leave away from a computer but I am now back and will hopefully find some time to take a look at this issue (along with adding python 3 compatibility).

Thanks

**Comment by manderso7** [comment]
Thanks Chris, I appreciate it.

**Comment by ChrisYounger** [comment]
This issue is now fixed in code
