### ISSUE TITLE
Splunk 9.3 breaks app

### ISSUE THREAD

**Issue by jackammerman** [ChrisYounger/git_for_splunk#10]
In Splunk 9.3, the python version setting defaults to Python 3.9. After upgrading I noticed git_for_splunk stopped working. I was getting the following error:
AttributeError: module 'time' has no attribute 'clock'

There are two references to time.clock() in input_module_gitforsplunk.py. I changed these to time.time() and the app appears to be working again.

I believe time.clock() was deprecated in Python 3.8 and the default Python version prior to Splunk 9.3 was Python 3.7. You can get around the default version setting as stated here https://docs.splunk.com/Documentation/Splunk/9.3.0/Python3Migration/ChangesEnterprise

**Comment by ChrisYounger** [comment]
Thank you for reporting this jackammerman. I have fixed it and put a new version on Splunkbase. Thanks again!
