### ISSUE TITLE
Modular input OUTPUT: Host key verification failed.

### ISSUE THREAD

**Issue by dimarra** [ChrisYounger/git_for_splunk#6]
Trying this on a Windows 10 environment before implementing on a Windows Server Test environment .  Splunk is running as a windows service started manually.

Under git bash,  I am able to successfully push to remote.  However, the modular input is reporting the issue below.  

```
EXITCODE: 0
repo_size=46568378
COMMAND: git push
OUTPUT:
Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

 cat ~/.ssh/known_hosts
shows the host key for the repo.  

How can i confirm the modular input is looking at the same known_host file? How do you turn up the debug logs?

Thanks

**Comment by ChrisYounger** [comment]
Hmm I am not sure the exact location, but this article seems like it should hopefully tell you: https://startbigthinksmall.wordpress.com/2012/04/26/how-to-authorize-local-system-account-for-openssh/

**Comment by dimarra** [comment]
Hi Chris. Thanks for point me in that direction.  Its been resolved now. 
Cheers
