### ISSUE TITLE
Request to add git show to the indexed logs

### ISSUE THREAD

**Issue by dougkamm** [ChrisYounger/git_for_splunk#7]
Could you please add the print of:
git --git-dir=/opt/splunk/etc/.git show

to the index logs Then would have what was changed within the changed_files.

**Comment by ChrisYounger** [comment]
Hi Dougkamm,

Thanks for this suggestion. I didn't originally add this feature becuase I was expecting that most people would be pushing to a remote repository (e.g. bitbucket, gitlab, github, gogs etc) and that this system will provide a much nicer git diffing experience.   

If you really want this feature, it would be best to add it yourself. In this file: https://github.com/ChrisYounger/git_for_splunk/blob/master/bin/input_module_gitforsplunk.py add the following at line 99:

```
ret_code, ret_output = gitcmd(["git", "show"], my_env, event_data)
```

I think that should do it  (you dont need the --git-dir becuase that is already set as an environment variable)

**Comment by dougkamm** [comment]
Awesome thanks.  What I’m struggling with is I’d like to have your app on all our machines and the search heads & indexers are in a DMZ with port 22 blocked so I’m not sure how to push to a remote repo on those so I’m going to try an all in Splunk solution 1st.  Thanks soo much for the code.  I’ll give that a try as soon as I can.

**Comment by dougkamm** [comment]
Hi,

After using this for a month we really like the results; however, are seeing truncating.  I’m hesitant to increase the truncation in fear of using too much of our license.  Would it be possible to filter the below code to only .conf or .meta files and exclude csv etc? or at least filter to just apps we manage and ignore system apps?

Thanks,

From: Kamm, Doug R
Sent: Thursday, October 29, 2020 8:13 AM
To: 'ChrisYounger/git_for_splunk' <reply@reply.github.com>
Subject: RE: [EXTERNAL] Re: [ChrisYounger/git_for_splunk] Request to add git show to the indexed logs (#7)

Awesome thanks.  What I’m struggling with is I’d like to have your app on all our machines and the search heads & indexers are in a DMZ with port 22 blocked so I’m not sure how to push to a remote repo on those so I’m going to try an all in Splunk solution 1st.  Thanks soo much for the code.  I’ll give that a try as soon as I can.

**Comment by ChrisYounger** [comment]
Hi mate. three options:

1. use .gitignore to only track changes to apps and files that you care about. this is standard git feature and not park of my app.
2. increase the TRUNCATE in props.conf (but obviously as you mentioned you might end up with some very large commits that use license. however these shouldn't be happening regularly).
3. (dubious) if you log to _internal, it wont hit license, but it will use storage.

Hope this helps

**Comment by dougkamm** [comment]
I’ve updated the following to our gitignore:

**/lookups/*
!apps/(apps we use)/lookups/*.csv
etc/auth/
etc/passwd
*.pyc
*.log
users/**/history/*
login-info.cfg
local.meta
ui-prefs.conf
telemetry.conf

If this is still too much data, I’ll try increasing our truncate and decrease the index internal to only a few times a day instead of every hour.

Thanks,
