### ISSUE TITLE
Git Specify Dir

### ISSUE THREAD

**Issue by edcaruso** [ChrisYounger/git_for_splunk#8]
Hey Chris/team,

I was about to write my own app to do just this but you saved me a ton of time! I want to know (and I couldn’t see any clear answer) if there is a way to specify a directory in git that the files get backed-up to.

In our Git Repo for example we have a folder for Search Heads and another for Heavy Forwarder. If I want to backup just the Heavy Forwarder config’s, I want them to be placed in the HF dir?

Any help would be amazing :)

Thanks

**Comment by ChrisYounger** [comment]
I am not sure I totally understand what you mean regarding having directories that files get backed-up to. This app is a simple automation over normal git.  

If you want to track changes in two separate directories, then you can either setup two separate repositories (and two "inputs" in the git_for_splunk app) or you can just have one repo, (at a high parent directory level) then setup .gitignore correctly to only track the directories you are interested in.

Hope this helps.

**Comment by edcaruso** [comment]
Hey Chris, 

Thanks for getting back to me so quickly. I think I am using git in a kind of un-common way. Let me elaborate. 

In our Git Repo currently we have the following folders:

**Master Repo Folders**:
      SH
      HF
      IDX 
     Other

What I would like to do is on my heavy forwarder, install your app and have it backup to the HF folder in my master repo. So basically, I want to specify the folder it gets backed up to instead of having an entire repo dedicated for the Heavy Forwarder. 

I hope that makes a bit more sense.

**Comment by ChrisYounger** [comment]
OK I think I understand. I don't think this is possible though. You would need to use separate repos.

**Comment by edcaruso** [comment]
Thanks. That’s what I thought but I was hoping away around that.

Thanks for this great Addon!
